# Generated by Django 5.2.4 on 2025-07-28 11:11

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageGenerationConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('max_images', models.PositiveIntegerField(default=4)),
            ],
        ),
        migrations.CreateModel(
            name='AnonymousUserToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(unique=True)),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('token_count', models.PositiveIntegerField(default=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'indexes': [models.Index(fields=['ip_address'], name='project_ano_ip_addr_493397_idx')],
                'unique_together': {('ip_address',)},
            },
        ),
        migrations.CreateModel(
            name='UserSubjectHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(blank=True, max_length=500, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('anon_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='project.anonymoususertoken')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prompt', models.TextField(blank=True, null=True)),
                ('image_url', models.JSONField(blank=True, default=list, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('prompt_subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='histories', to='project.usersubjecthistory')),
            ],
        ),
    ]
